### ISSUE TITLE
RingAlarm fails to start, error on startup

### ISSUE THREAD

**Issue by markcarroll** [dgreif/ring-alarm#32]
I am getting the following error trying to add my Ring Doorbell:

```
[6/16/2019, 9:11:59 PM] [RingAlarm] Configuring 1 cameras and 0 devices for locationId c290hb-2s0fi-0
[6/16/2019, 9:11:59 PM] [RingAlarm] Adding new accessory lpd_v2 Front Door
[6/16/2019, 9:11:59 PM] [RingAlarm] Error connecting to API
[6/16/2019, 9:11:59 PM] [RingAlarm] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: f0c6f4aa-3193-4b9d-8a8f-4127cf8ceb8e
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:268:13)
    at Bridge.Accessory.addBridgedAccessories (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:299:10)
    at Server._handleRegisterPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:490:16)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:41:10)
    at API.emit (events.js:198:13)
    at API.registerPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/api.js:171:8)
    at createHomebridgeAccessory (/homebridge/node_modules/homebridge-ring-alarm/homebridge/ring-alarm-platform.js:98:29)
    at allDevices.forEach.device (/homebridge/node_modules/homebridge-ring-alarm/homebridge/ring-alarm-platform.js:100:82)
    at Array.forEach (<anonymous>)
    at RingAlarmPlatform.<anonymous> (/homebridge/node_modules/homebridge-ring-alarm/homebridge/ring-alarm-platform.js:88:28)
    at Generator.next (<anonymous>)
    at fulfilled (/homebridge/node_modules/homebridge-ring-alarm/homebridge/ring-alarm-platform.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Here is my config:

```
        {
            "platform": "RingAlarm",
            "name": "RingAlarm",
            "email": "mark@site.me",
            "password": "******",
            "beamDurationSeconds": 60,
            "hideLightGroups": true,
            "cameraStatusPollingSeconds": 30,
            "cameraDingsPollingSeconds": 5
        },
```

**Comment by dgreif** [comment]
@markcarroll I haven't seen an error like this yet, but my guess is that you have/had one of the other ring camera homebridge plugins installed.  Can you confirm whether or not this is the case?  If so, you will need to remove the other ring plugin from your config and restart homebridge.  If the error continues, your next step will be to delete the ~/.homebridge/accessories directory.  I try to avoid deleting that directory as it can mess up any automations you have set up with homebridge devices, so let me know if it works without deleting that.

**Comment by markcarroll** [comment]
That was the problem. I deleted the accessories file (after checking to see what I would lose) and restarted. It fired up successfully.  I still do not see the camera in HomeKit but that is another issue. Thanks for the help.
