### ISSUE TITLE
more than one homebridge instance not starting

### ISSUE THREAD

**Issue by divemasterjm** [dgreif/ring-alarm#40]
hi i have 4 homebridge instances, therefore same plugins are shared but in the plugins where there is not ringalarm platform in the config they cant start due to the following error on start up
Load homebridge-ring-alarm.RingAlarm
[6/24/2019, 6:26:31 PM] TypeError: Cannot read property 'cameraStatusPollingSeconds' of null
    at new RingAlarmPlatform (/usr/local/lib/node_modules/homebridge-ring-alarm/homebridge/ring-alarm-platform.js:64:52)
    at Server._loadDynamicPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:358:30)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:92:8)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at executeUserCode (internal/bootstrap/node.js:342:17)
    at startExecution (internal/bootstrap/node.js:276:5)
    at startup (internal/bootstrap/node.js:227:5)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

is like you need the platform entry on the config even if you dont use it in this instance

**Comment by dgreif** [comment]
That's really odd.  Looks like homebridge will call the `platformConstructor` with `null` config if it finds the plugin but it isn't configured (https://github.com/nfarina/homebridge/blob/84b4733ac75aba9e7c19d36be282cd8162077860/lib/server.js#L358).  Had no idea it could do that.  I'll add a check to make sure there is a config and just return out if there isn't.

That seems like an odd setup.  Just curious, what lead you to need 4 homebridge instances?

**Comment by divemasterjm** [comment]
hi, others plugins works flawesly, i have 4 instances for various reasons, more than 100 accesories and specially cameras, if they have a problem homebridge becomes in "not responding state".

**Comment by divemasterjm** [comment]
meantime like workaround i wrote in all other configs a platform with bad user/pw, ive got and error but starts

**Comment by dgreif** [comment]
@divemasterjm give `v3.2.1` a try.  Should just see a log that says there is no config, with no error taking down the homebridge instance.

**Comment by BradMcGonigle** [comment]
> give v3.2.1 a try

This solved the issue for me. Thanks for the quick update!

**Comment by divemasterjm** [comment]
tried and solved the issue. Thanks for the quick update!

**Comment by dgreif** [comment]
No problem, glad it was an easy fix ✅
